export const AllItems = [
    'Absolite',
    'Absorb Bulb',
    'Adrenaline Orb',
    'Aerodactylite',
    'Air Balloon',
    'Alakazite',
    'Altarianite',
    'Ampharosite',
    'Apicot Berry',
    'Aspear Berry',
    'Audinite',
    'Babiri Berry',
    'Banettite',
    'Beedrillite',
    'Big Root',
    'Binding Band',
    'Black Belt',
    'Black Glasses',
    'Blunder Policy',
    'Bright Powder',
    'Bug Gem',
    'Burn Drive',
    'Cameruptite',
    'Cell Battery',
    'Charcoal',
    'Charti Berry',
    'Cheri Berry',
    'Chesto Berry',
    'Chilan Berry',
    'Chill Drive',
    'Choice Band',
    'Choice Scarf',
    'Choice Specs',
    'Chople Berry',
    'Coba Berry',
    'Colbur Berry',
    'Custap Berry',
    'Damp Rock',
    'Dark Gem',
    'Deep Sea Scale',
    'Deep Sea Tooth',
    'Destiny Knot',
    'Douse Drive',
    'Draco Plate',
    'Dragon Fang',
    'Dragon Gem',
    'Dread Plate',
    'Earth Plate',
    'Eject Button',
    'Eject Pack',
    'Electric Gem',
    'Electric Seed',
    'Eviolite',
    'Expert Belt',
    'Fairy Gem',
    'Fighting Gem',
    'Fire Gem',
    'Fist Plate',
    'Flame Orb',
    'Flame Plate',
    'Float Stone',
    'Flying Gem',
    'Focus Band',
    'Focus Sash',
    'Full Incense',
    'Galladite',
    'Ganlon Berry',
    'Gardevoirite',
    'Gengarite',
    'Ghost Gem',
    'Glalitite',
    'Grass Gem',
    'Grassy Seed',
    'Grip Claw',
    'Ground Gem',
    'Haban Berry',
    'Hard Stone',
    'Heat Rock',
    'Heavy-Duty Boots',
    'Heracronite',
    'Houndoominite',
    'Ice Gem',
    'Icicle Plate',
    'Icy Rock',
    'Insect Plate',
    'Iron Ball',
    'Iron Plate',
    'Jaboca Berry',
    'Kasib Berry',
    'Kebia Berry',
    'Kee Berry',
    'Kings Rock',
    'Lagging Tail',
    'Lansat Berry',
    'Lax Incense',
    'Leppa Berry',
    'Liechi Berry',
    'Life Orb',
    'Light Ball',
    'Light Clay',
    'Lopunnite',
    'Lucky Punch',
    'Lum Berry',
    'Luminous Moss',
    'Magnet',
    'Manectite',
    'Maranga Berry',
    'Meadow Plate',
    'Mental Herb',
    'Metal Coat',
    'Metal Powder',
    'Metronome',
    'Micle Berry',
    'Mind Plate',
    'Miracle Seed',
    'Misty Seed',
    'Muscle Band',
    'Mystic Water',
    'Never-Melt Ice',
    'Normal Gem',
    'Normalium Z',
    'Occa Berry',
    'Odd Incense',
    'Passho Berry',
    'Payapa Berry',
    'Pecha Berry',
    'Persim Berry',
    'Petaya Berry',
    'Pidgeotite',
    'Pinsirite',
    'Pixie Plate',
    'Poison Barb',
    'Poison Gem',
    'Power Herb',
    'Protective Pads',
    'Psychic Gem',
    'Psychic Seed',
    'Quick Claw',
    'Quick Powder',
    'Rawst Berry',
    'Red Card',
    'Rindo Berry',
    'Ring Target',
    'Rock Gem',
    'Rock Incense',
    'Room Service',
    'Rose Incense',
    'Roseli Berry',
    'Rowap Berry',
    'Rusted Shield',
    'Rusted Sword',
    'Sablenite',
    'Safety Goggles',
    'Salac Berry',
    'Scope Lens',
    'Sea Incense',
    'Sharp Beak',
    'Sharpedonite',
    'Shed Shell',
    'Shock Drive',
    'Shuca Berry',
    'Silk Scarf',
    'Silver Powder',
    'Sky Plate',
    'Slowbronite',
    'Smoke Ball',
    'Smooth Rock',
    'Snowball',
    'Soft Sand',
    'Spell Tag',
    'Splash Plate',
    'Spooky Plate',
    'Starf Berry',
    'Steel Gem',
    'Stick',
    'Sticky Barb',
    'Stone Plate',
    'Tanga Berry',
    'Terrain Extender',
    'Thick Club',
    'Throat Spray',
    'Toxic Orb',
    'Toxic Plate',
    'Twisted Spoon',
    'Utility Umbrella',
    'Venusaurite',
    'Wacan Berry',
    'Water Gem',
    'Wave Incense',
    'Weakness Policy',
    'White Herb',
    'Wide Lens',
    'Wise Glasses',
    'Yache Berry',
    'Zap Plate',
    'Zoom Lens'
];
